# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        
on:
  push:
    branches: 
        - master
        - devel
  pull_request:
    branches: 
        - master
        - devel

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        r-version: [4.0]

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up R ${{ matrix.r-version }} 
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install py dependency
        run: /usr/bin/python3 -m pip install numpy scipy pandas
      - name: Install bash dependencies 1
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: Install reticulate
        run: |
            install.packages('reticulate', repos = "http://cran.us.r-project.org")
            reticulate::py_config()
            reticulate::use_python("/usr/bin/python3")
            reticulate::py_config()
        shell: sudo Rscript {0}
      - name: Install dependencies 2
        run: |
            install.packages(c("remotes", "rcmdcheck"), repos = "http://cran.us.r-project.org")
            remotes::install_deps(dep = T)
        shell: sudo Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual","--ignore-vignettes"), error_on = "error", build_args="--no-build-vignettes")
        shell: sudo Rscript {0}
      - name: Report coverage
        run: |
           - Rscript coverZoo.r
