# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: netZooR

env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
on:
  push:
    branches: 
        - master
        - devel
  pull_request:
    branches: 
        - master
        - devel

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        r-version: [4.1]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up R ${{ matrix.r-version }} 
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
             any::reticulate
             any::rcmdcheck
             any::covr
          needs: |
             website
             coverage
      - name: Install reticulate 1
        run: |
            library('reticulate')
        shell: Rscript {0}
      - name: Install reticulate 2-1
        if: matrix.os == 'macos-latest'
        run: |
            library('reticulate')
            py_config()
            use_python("/usr/local/bin/python3")
            virtualenv_create("r-reticulate")
        shell: sudo -E Rscript {0}
      - name: Install reticulate 2-2
        if: matrix.os == 'ubuntu-latest'
        run: |
            library('reticulate')
            py_config()
            use_python("/usr/bin/python3")
            virtualenv_create("r-reticulate")
        shell: sudo -E Rscript {0}
      - name: Install reticulate 3
        run: |
            library('reticulate')
            virtualenv_install("r-reticulate","numpy")
            virtualenv_install("r-reticulate","scipy")
            virtualenv_install("r-reticulate","pandas")
            virtualenv_install("r-reticulate","joblib")
        shell: sudo -E Rscript {0}
      - name: Check
        run: |
            library('reticulate')
            py_config()
            rcmdcheck::rcmdcheck(args = c("--no-manual","--ignore-vignettes"), error_on = "error", build_args="--no-build-vignettes")
        shell: sudo -E Rscript {0}
      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
      - name: Report coverage
        run: |
            covr::codecov()
        shell: Rscript {0}

